### ISSUE TITLE
Can't start redis-server

### ISSUE THREAD

**Issue by Ruriko** [geraldwuhoo/omgur#9] opened 2022-03-23 10:13 UTC
I'm trying to run redis-server but I get this error:
```
15350:C 23 Mar 2022 11:05:07.257 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
15350:C 23 Mar 2022 11:05:07.257 # Redis version=6.2.6, bits=64, commit=00000000, modified=0, pid=15350, just started
15350:C 23 Mar 2022 11:05:07.257 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
15350:M 23 Mar 2022 11:05:07.258 * monotonic clock: POSIX clock_gettime
15350:M 23 Mar 2022 11:05:07.258 # Warning: Could not create server TCP listening socket *:6379: bind: Address already in use
15350:M 23 Mar 2022 11:05:07.258 # Failed listening on port 6379 (TCP), aborting.
```
How to fix this?

**Comment by geraldwuhoo** [comment] 2022-03-23 10:18
> `Could not create server TCP listening socket *:6379: bind: Address already in use`

It looks like in that you already have another service listening on port 6379 (possibly an existing Redis instance?). This has to do with running Redis and isn't caused by Omgur, so I'm going to go ahead and close this issue.

P.S. Docker is made for situations like this (running multiple instances of services on one machine hassle-free), I highly recommend looking into it so you can use the included `Dockerfile` and `docker-compose.yaml`.

**Closed as completed by geraldwuhoo** 2022-03-23 10:18 UTC

**Comment by Ruriko** [comment] 2022-03-23 10:33
@geraldwuhoo is there a way to change the redis port? I've tried to edit the port in app.go file but it still tries to connect to port 6379

**Comment by geraldwuhoo** [comment] 2022-03-23 19:02
Yes, you can set the redit host and port through environment variables `REDIS_HOST` and `REDIS_PORT` respectively: https://github.com/geraldwuhoo/omgur/blob/5f7b2e2b9a25068bc0edee9f393d964a849ed25c/pkg/app/app.go#L28-L32

**Comment by geraldwuhoo** [comment] 2022-03-23 19:10
If you are referring to how to run the redis-server itself listening on a different port, I'll have to refer you to the Redis documentation https://redis.io/docs/manual/config/. Setting up Redis itself has nothing to do with Omgur &mdash; Omgur is merely configured to connect to an existing Redis instance. Setting up Redis is left as an exercise to the reader.
